mv "content/images/2aF/2aF-scaled.png" "content/images/2aF/net.retorx.processedImages" 
mv "content/images/A and R rep/A and R rep-scaled.png" "content/images/A and R rep/net.retorx.processedImages" 
mv "content/images/abstract color I/abstract color I-scaled.png" "content/images/abstract color I/net.retorx.processedImages" 
mv "content/images/abstract color II/abstract color II-scaled.png" "content/images/abstract color II/net.retorx.processedImages" 
mv "content/images/abstract color III/abstract color III-scaled.png" "content/images/abstract color III/net.retorx.processedImages" 
mv "content/images/angel I/angel I aux-scaled.png" "content/images/angel I/net.retorx.processedImages" 
mv "content/images/angel I/angel I-scaled.png" "content/images/angel I/net.retorx.processedImages" 
mv "content/images/anger/anger-scaled.png" "content/images/anger/net.retorx.processedImages" 
mv "content/images/ascention to the cross/ascention to the cross-scaled.png" "content/images/ascention to the cross/net.retorx.processedImages" 
mv "content/images/athlete/athlete aux-scaled.png" "content/images/athlete/net.retorx.processedImages" 
mv "content/images/athlete/athlete aux2-scaled.png" "content/images/athlete/net.retorx.processedImages" 
mv "content/images/athlete/athlete-scaled.png" "content/images/athlete/net.retorx.processedImages" 
mv "content/images/back/back aux-scaled.png" "content/images/back/net.retorx.processedImages" 
mv "content/images/back/back-scaled.png" "content/images/back/net.retorx.processedImages" 
mv "content/images/blade/blade-scaled.png" "content/images/blade/net.retorx.processedImages" 
mv "content/images/body in rejection/body in rejection aux1-scaled.png" "content/images/body in rejection/net.retorx.processedImages" 
mv "content/images/body in rejection/body in rejection aux2-scaled.png" "content/images/body in rejection/net.retorx.processedImages" 
mv "content/images/body in rejection/body in rejection-scaled.png" "content/images/body in rejection/net.retorx.processedImages" 
mv "content/images/burn I/burn I-scaled.png" "content/images/burn I/net.retorx.processedImages" 
mv "content/images/call III/call III-scaled.png" "content/images/call III/net.retorx.processedImages" 
mv "content/images/cheney rodeo/cheney rodeo-scaled.png" "content/images/cheney rodeo/net.retorx.processedImages" 
mv "content/images/choking hazard/choking hazard-scaled.png" "content/images/choking hazard/net.retorx.processedImages" 
mv "content/images/christ II/christ II-scaled.png" "content/images/christ II/net.retorx.processedImages" 
mv "content/images/clean I/clean I-scaled.png" "content/images/clean I/net.retorx.processedImages" 
mv "content/images/cleanliness is next/cleanliness is next-scaled.png" "content/images/cleanliness is next/net.retorx.processedImages" 
mv "content/images/Connected Figure/Connected Figure-scaled.png" "content/images/Connected Figure/net.retorx.processedImages" 
mv "content/images/Connected Figure O/Connected Figure O-scaled.png" "content/images/Connected Figure O/net.retorx.processedImages" 
mv "content/images/Construction of Female VI/Construction of Female VI-scaled.png" "content/images/Construction of Female VI/net.retorx.processedImages" 
mv "content/images/Construction of Figure in Transition/Construction of Figure in Transition-scaled.png" "content/images/Construction of Figure in Transition/net.retorx.processedImages" 
mv "content/images/Construction of Two Females/Construction of Two Females-scaled.png" "content/images/Construction of Two Females/net.retorx.processedImages" 
mv "content/images/Corrupted Study I/Corrupted Study I-scaled.png" "content/images/Corrupted Study I/net.retorx.processedImages" 
mv "content/images/Corrupted Study II/Corrupted Study II-scaled.png" "content/images/Corrupted Study II/net.retorx.processedImages" 
mv "content/images/curl/curl-scaled.png" "content/images/curl/net.retorx.processedImages" 
mv "content/images/dancer/dancer-scaled.png" "content/images/dancer/net.retorx.processedImages" 
mv "content/images/Descension/Descension-scaled.png" "content/images/Descension/net.retorx.processedImages" 
mv "content/images/drift/drift-scaled.png" "content/images/drift/net.retorx.processedImages" 
mv "content/images/drone I/drone I aux2-scaled.png" "content/images/drone I/net.retorx.processedImages" 
mv "content/images/drone I/drone I aux5-scaled.png" "content/images/drone I/net.retorx.processedImages" 
mv "content/images/drone I/drone I aux6-scaled.png" "content/images/drone I/net.retorx.processedImages" 
mv "content/images/drone I/drone I-scaled.png" "content/images/drone I/net.retorx.processedImages" 
mv "content/images/drone II/drone II aux-scaled.png" "content/images/drone II/net.retorx.processedImages" 
mv "content/images/drone II/drone II aux2-scaled.png" "content/images/drone II/net.retorx.processedImages" 
mv "content/images/drone II/drone II-scaled.png" "content/images/drone II/net.retorx.processedImages" 
mv "content/images/drone III/drone III aux-scaled.png" "content/images/drone III/net.retorx.processedImages" 
mv "content/images/drone III/drone III-scaled.png" "content/images/drone III/net.retorx.processedImages" 
mv "content/images/drone IV/drone IV aux-scaled.png" "content/images/drone IV/net.retorx.processedImages" 
mv "content/images/drone IV/drone IV aux2-scaled.png" "content/images/drone IV/net.retorx.processedImages" 
mv "content/images/drone IV/drone IV aux3-scaled.png" "content/images/drone IV/net.retorx.processedImages" 
mv "content/images/drone IV/drone IV-scaled.png" "content/images/drone IV/net.retorx.processedImages" 
mv "content/images/dup rejesus process/dup rejesus process aux-scaled.png" "content/images/dup rejesus process/net.retorx.processedImages" 
mv "content/images/dup rejesus process/dup rejesus process aux2-scaled.png" "content/images/dup rejesus process/net.retorx.processedImages" 
mv "content/images/dup rejesus process/dup rejesus process-scaled.png" "content/images/dup rejesus process/net.retorx.processedImages" 
mv "content/images/face II/face II-scaled.png" "content/images/face II/net.retorx.processedImages" 
mv "content/images/face III/face III-scaled.png" "content/images/face III/net.retorx.processedImages" 
mv "content/images/face IV/face IV-scaled.png" "content/images/face IV/net.retorx.processedImages" 
mv "content/images/Female Figure at Transition/Female Figure at Transition-scaled.png" "content/images/Female Figure at Transition/net.retorx.processedImages" 
mv "content/images/Figure Asleep/Figure Asleep-scaled.png" "content/images/Figure Asleep/net.retorx.processedImages" 
mv "content/images/Figure In Progress/Figure In Progress-scaled.png" "content/images/Figure In Progress/net.retorx.processedImages" 
mv "content/images/Figure In Progress II/Figure In Progress II-scaled.png" "content/images/Figure In Progress II/net.retorx.processedImages" 
mv "content/images/filter/filter aux-scaled.png" "content/images/filter/net.retorx.processedImages" 
mv "content/images/filter/filter-scaled.png" "content/images/filter/net.retorx.processedImages" 
mv "content/images/Fox News/Fox News-scaled.png" "content/images/Fox News/net.retorx.processedImages" 
mv "content/images/girl drowning in walk I/girl drowning in walk I aux-scaled.png" "content/images/girl drowning in walk I/net.retorx.processedImages" 
mv "content/images/girl drowning in walk I/girl drowning in walk I aux2-scaled.png" "content/images/girl drowning in walk I/net.retorx.processedImages" 
mv "content/images/girl drowning in walk I/girl drowning in walk I-scaled.png" "content/images/girl drowning in walk I/net.retorx.processedImages" 
mv "content/images/girl drowning in walk II/girl drowning in walk II aux2-scaled.png" "content/images/girl drowning in walk II/net.retorx.processedImages" 
mv "content/images/girl drowning in walk II/girl drowning in walk II aux3-scaled.png" "content/images/girl drowning in walk II/net.retorx.processedImages" 
mv "content/images/girl drowning in walk II/girl drowning in walk II-scaled.png" "content/images/girl drowning in walk II/net.retorx.processedImages" 
mv "content/images/girl with magic/girl with magic aux1-scaled.png" "content/images/girl with magic/net.retorx.processedImages" 
mv "content/images/girl with magic/girl with magic-scaled.png" "content/images/girl with magic/net.retorx.processedImages" 
mv "content/images/gunship/gunship-scaled.png" "content/images/gunship/net.retorx.processedImages" 
mv "content/images/hard wired gun/hard wired gun aux-scaled.png" "content/images/hard wired gun/net.retorx.processedImages" 
mv "content/images/hard wired gun/hard wired gun aux2-scaled.png" "content/images/hard wired gun/net.retorx.processedImages" 
mv "content/images/hard wired gun/hard wired gun-scaled.png" "content/images/hard wired gun/net.retorx.processedImages" 
mv "content/images/hidden II/hidden II-scaled.png" "content/images/hidden II/net.retorx.processedImages" 
mv "content/images/High Density Polyethylene/High Density Polyethylene-scaled.png" "content/images/High Density Polyethylene/net.retorx.processedImages" 
mv "content/images/holy machine I/holy machine I aux-scaled.png" "content/images/holy machine I/net.retorx.processedImages" 
mv "content/images/holy machine I/holy machine I aux2-scaled.png" "content/images/holy machine I/net.retorx.processedImages" 
mv "content/images/holy machine I/holy machine I aux4-scaled.png" "content/images/holy machine I/net.retorx.processedImages" 
mv "content/images/holy machine I/holy machine I-scaled.png" "content/images/holy machine I/net.retorx.processedImages" 
mv "content/images/hue filter/hue filter-scaled.png" "content/images/hue filter/net.retorx.processedImages" 
mv "content/images/I am the King/I am the King-scaled.png" "content/images/I am the King/net.retorx.processedImages" 
mv "content/images/iconography I/iconography aux-scaled.png" "content/images/iconography I/net.retorx.processedImages" 
mv "content/images/iconography I/iconography I-scaled.png" "content/images/iconography I/net.retorx.processedImages" 
mv "content/images/identify/identify aux-scaled.png" "content/images/identify/net.retorx.processedImages" 
mv "content/images/identify/identify-scaled.png" "content/images/identify/net.retorx.processedImages" 
mv "content/images/inherent burn/inherent burn-scaled.png" "content/images/inherent burn/net.retorx.processedImages" 
mv "content/images/inherent light/inherent light-scaled.png" "content/images/inherent light/net.retorx.processedImages" 
mv "content/images/insect I/insect I-scaled.png" "content/images/insect I/net.retorx.processedImages" 
mv "content/images/insect II/insect II-scaled.png" "content/images/insect II/net.retorx.processedImages" 
mv "content/images/insect III/insect III-scaled.png" "content/images/insect III/net.retorx.processedImages" 
mv "content/images/insect IV/insect IV-scaled.png" "content/images/insect IV/net.retorx.processedImages" 
mv "content/images/insect V red/insect V red-scaled.png" "content/images/insect V red/net.retorx.processedImages" 
mv "content/images/Lambs of Abortion flyer - April 11 2009/Lambs of Abortion flyer - April 11 2009-scaled.png" "content/images/Lambs of Abortion flyer - April 11 2009/net.retorx.processedImages" 
mv "content/images/Lambs of Abortion flyer - August 14 2009/Lambs of Abortion flyer - August 14 2009-scaled.png" "content/images/Lambs of Abortion flyer - August 14 2009/net.retorx.processedImages" 
mv "content/images/Lambs of Abortion flyer - January 31 2009/Lambs of Abortion flyer - January 31 2009-scaled.png" "content/images/Lambs of Abortion flyer - January 31 2009/net.retorx.processedImages" 
mv "content/images/Lambs of Abortion flyer - May 23 2009/Lambs of Abortion flyer - May 23 2009-scaled.png" "content/images/Lambs of Abortion flyer - May 23 2009/net.retorx.processedImages" 
mv "content/images/Lambs of Abortion flyer - September 9 2008/Lambs of Abortion flyer - September 9 2008-scaled.png" "content/images/Lambs of Abortion flyer - September 9 2008/net.retorx.processedImages" 
mv "content/images/landscape II/landscape II-scaled.png" "content/images/landscape II/net.retorx.processedImages" 
mv "content/images/leaping girl/leaping girl aux1-scaled.png" "content/images/leaping girl/net.retorx.processedImages" 
mv "content/images/leaping girl/leaping girl aux2-scaled.png" "content/images/leaping girl/net.retorx.processedImages" 
mv "content/images/leaping girl/leaping girl aux3-scaled.png" "content/images/leaping girl/net.retorx.processedImages" 
mv "content/images/leaping girl/leaping girl-scaled.png" "content/images/leaping girl/net.retorx.processedImages" 
mv "content/images/light, movement/light, movement II aux-scaled.png" "content/images/light, movement/net.retorx.processedImages" 
mv "content/images/light, movement/light, movement II aux2-scaled.png" "content/images/light, movement/net.retorx.processedImages" 
mv "content/images/light, movement/light, movement-scaled.png" "content/images/light, movement/net.retorx.processedImages" 
mv "content/images/light, movement II/light, movement II-scaled.png" "content/images/light, movement II/net.retorx.processedImages" 
mv "content/images/liquid/liquid-scaled.png" "content/images/liquid/net.retorx.processedImages" 
mv "content/images/man standing/man standing-scaled.png" "content/images/man standing/net.retorx.processedImages" 
mv "content/images/medic/medic-scaled.png" "content/images/medic/net.retorx.processedImages" 
mv "content/images/mercy seat/mercy seat aux1-scaled.png" "content/images/mercy seat/net.retorx.processedImages" 
mv "content/images/mercy seat/mercy seat-scaled.png" "content/images/mercy seat/net.retorx.processedImages" 
mv "content/images/messianic/messianic-scaled.png" "content/images/messianic/net.retorx.processedImages" 
mv "content/images/mind fault/mind fault-scaled.png" "content/images/mind fault/net.retorx.processedImages" 
mv "content/images/mind fault II/mind fault II-scaled.png" "content/images/mind fault II/net.retorx.processedImages" 
mv "content/images/MS II/MS II-scaled.png" "content/images/MS II/net.retorx.processedImages" 
mv "content/images/opec collaborate opiate cancer moloch/opec collaborate opiate cancer moloch-scaled.png" "content/images/opec collaborate opiate cancer moloch/net.retorx.processedImages" 
mv "content/images/particle collision - connection XII/particle collision - connection XII-scaled.png" "content/images/particle collision - connection XII/net.retorx.processedImages" 
mv "content/images/plate/plate-scaled.png" "content/images/plate/net.retorx.processedImages" 
mv "content/images/plate form/plate form-scaled.png" "content/images/plate form/net.retorx.processedImages" 
mv "content/images/political salvo crown/political salvo crown aux-scaled.png" "content/images/political salvo crown/net.retorx.processedImages" 
mv "content/images/political salvo crown/political salvo crown aux2-scaled.png" "content/images/political salvo crown/net.retorx.processedImages" 
mv "content/images/political salvo crown/political salvo crown-scaled.png" "content/images/political salvo crown/net.retorx.processedImages" 
mv "content/images/Prototype/Prototype-scaled.png" "content/images/Prototype/net.retorx.processedImages" 
mv "content/images/pump six/pump six aux-scaled.png" "content/images/pump six/net.retorx.processedImages" 
mv "content/images/pump six/pump six aux2-scaled.png" "content/images/pump six/net.retorx.processedImages" 
mv "content/images/pump six/pump six-scaled.png" "content/images/pump six/net.retorx.processedImages" 
mv "content/images/reclining figure II/reclining figure II-scaled.png" "content/images/reclining figure II/net.retorx.processedImages" 
mv "content/images/Religious Figure/Religious Figure-scaled.png" "content/images/Religious Figure/net.retorx.processedImages" 
mv "content/images/sigma edit/sigma edit-scaled.png" "content/images/sigma edit/net.retorx.processedImages" 
mv "content/images/sitting figure/sitting figure-scaled.png" "content/images/sitting figure/net.retorx.processedImages" 
mv "content/images/spill 0/spill 0-scaled.png" "content/images/spill 0/net.retorx.processedImages" 
mv "content/images/spill I/spill I aux-scaled.png" "content/images/spill I/net.retorx.processedImages" 
mv "content/images/spill I/spill I aux2-scaled.png" "content/images/spill I/net.retorx.processedImages" 
mv "content/images/spill I/spill I-scaled.png" "content/images/spill I/net.retorx.processedImages" 
mv "content/images/spill II/spill II aux-scaled.png" "content/images/spill II/net.retorx.processedImages" 
mv "content/images/spill II/spill II aux2-scaled.png" "content/images/spill II/net.retorx.processedImages" 
mv "content/images/spill II/spill II-scaled.png" "content/images/spill II/net.retorx.processedImages" 
mv "content/images/sprite figure/sprite figure-scaled.png" "content/images/sprite figure/net.retorx.processedImages" 
mv "content/images/Strangest Places flyer - April 3 2009/Strangest Places flyer - April 3 2009-scaled.png" "content/images/Strangest Places flyer - April 3 2009/net.retorx.processedImages" 
mv "content/images/Strangest Places flyer - February 2 2010/Strangest Places flyer - February 2 2010 aux-scaled.png" "content/images/Strangest Places flyer - February 2 2010/net.retorx.processedImages" 
mv "content/images/Strangest Places flyer - February 2 2010/Strangest Places flyer - February 2 2010-scaled.png" "content/images/Strangest Places flyer - February 2 2010/net.retorx.processedImages" 
mv "content/images/Strangest Places website design V/Strangest Places website design V-scaled.png" "content/images/Strangest Places website design V/net.retorx.processedImages" 
mv "content/images/subway IV/subway IV-scaled.png" "content/images/subway IV/net.retorx.processedImages" 
mv "content/images/Terminal Bliss album design II/Terminal Bliss album design II-scaled.png" "content/images/Terminal Bliss album design II/net.retorx.processedImages" 
mv "content/images/The Loa website graphic/The Loa website graphic-scaled.png" "content/images/The Loa website graphic/net.retorx.processedImages" 
mv "content/images/triptych/triptych-scaled.png" "content/images/triptych/net.retorx.processedImages" 
mv "content/images/Two Figures Aligned/Two Figures Aligned-scaled.png" "content/images/Two Figures Aligned/net.retorx.processedImages" 
mv "content/images/unit drop forge/unit drop forge-scaled.png" "content/images/unit drop forge/net.retorx.processedImages" 
mv "content/images/untitled body I/untitled body I-scaled.png" "content/images/untitled body I/net.retorx.processedImages" 
mv "content/images/untitled body II/untitled body II-scaled.png" "content/images/untitled body II/net.retorx.processedImages" 
mv "content/images/untitled body III/untitled body III-scaled.png" "content/images/untitled body III/net.retorx.processedImages" 
mv "content/images/untitled body IV/untitled body IV aux-scaled.png" "content/images/untitled body IV/net.retorx.processedImages" 
mv "content/images/untitled body IV/untitled body IV aux2-scaled.png" "content/images/untitled body IV/net.retorx.processedImages" 
mv "content/images/untitled body IV/untitled body IV-scaled.png" "content/images/untitled body IV/net.retorx.processedImages" 
mv "content/images/untitled connection I/untitled connection I-scaled.png" "content/images/untitled connection I/net.retorx.processedImages" 
mv "content/images/untitled connection II/untitled connection II aux-scaled.png" "content/images/untitled connection II/net.retorx.processedImages" 
mv "content/images/untitled connection II/untitled connection II aux2-scaled.png" "content/images/untitled connection II/net.retorx.processedImages" 
mv "content/images/untitled connection II/untitled connection II-scaled.png" "content/images/untitled connection II/net.retorx.processedImages" 
mv "content/images/untitled connection III/untitled connection III aux-scaled.png" "content/images/untitled connection III/net.retorx.processedImages" 
mv "content/images/untitled connection III/untitled connection III-scaled.png" "content/images/untitled connection III/net.retorx.processedImages" 
mv "content/images/untitled connection IX/untitled connection IX-scaled.png" "content/images/untitled connection IX/net.retorx.processedImages" 
mv "content/images/untitled connection kiss/untitled connection kiss-scaled.png" "content/images/untitled connection kiss/net.retorx.processedImages" 
mv "content/images/untitled connection V/untitled connection V aux-scaled.png" "content/images/untitled connection V/net.retorx.processedImages" 
mv "content/images/untitled connection V/untitled connection V aux2-scaled.png" "content/images/untitled connection V/net.retorx.processedImages" 
mv "content/images/untitled connection V/untitled connection V-scaled.png" "content/images/untitled connection V/net.retorx.processedImages" 
mv "content/images/untitled connection VI/untitled connection VI aux-scaled.png" "content/images/untitled connection VI/net.retorx.processedImages" 
mv "content/images/untitled connection VI/untitled connection VI-scaled.png" "content/images/untitled connection VI/net.retorx.processedImages" 
mv "content/images/untitled connection VII/untitled connection VII aux-scaled.png" "content/images/untitled connection VII/net.retorx.processedImages" 
mv "content/images/untitled connection VII/untitled connection VII-scaled.png" "content/images/untitled connection VII/net.retorx.processedImages" 
mv "content/images/untitled connection VIII/untitled connection VIII-scaled.png" "content/images/untitled connection VIII/net.retorx.processedImages" 
mv "content/images/untitled connection VIII/winter work-2-2-scaled.png" "content/images/untitled connection VIII/net.retorx.processedImages" 
mv "content/images/untitled connection VIII/winter work-3-scaled.png" "content/images/untitled connection VIII/net.retorx.processedImages" 
mv "content/images/untitled connection VIII/winter work-4-scaled.png" "content/images/untitled connection VIII/net.retorx.processedImages" 
mv "content/images/untitled connection VIII/winter work-5-scaled.png" "content/images/untitled connection VIII/net.retorx.processedImages" 
mv "content/images/untitled connection X/ntitled connection X aix-scaled.png" "content/images/untitled connection X/net.retorx.processedImages" 
mv "content/images/untitled connection X/untitled connection X aux6-scaled.png" "content/images/untitled connection X/net.retorx.processedImages" 
mv "content/images/untitled connection X/untitled connection X-scaled.png" "content/images/untitled connection X/net.retorx.processedImages" 
mv "content/images/untitled connection XI/untitled connection XI-scaled.png" "content/images/untitled connection XI/net.retorx.processedImages" 
mv "content/images/untitled crouching figure/untitled crouching figure-scaled.png" "content/images/untitled crouching figure/net.retorx.processedImages" 
mv "content/images/untitled dance I/untitled dance I aux-scaled.png" "content/images/untitled dance I/net.retorx.processedImages" 
mv "content/images/untitled dance I/untitled dance I aux2-scaled.png" "content/images/untitled dance I/net.retorx.processedImages" 
mv "content/images/untitled dance I/untitled dance I-scaled.png" "content/images/untitled dance I/net.retorx.processedImages" 
mv "content/images/untitled face III/untitled face III-scaled.png" "content/images/untitled face III/net.retorx.processedImages" 
mv "content/images/untitled fetish I/untitled fetish I aux-scaled.png" "content/images/untitled fetish I/net.retorx.processedImages" 
mv "content/images/untitled fetish I/untitled fetish I-scaled.png" "content/images/untitled fetish I/net.retorx.processedImages" 
mv "content/images/untitled figure drone III/untitled figure drone III-scaled.png" "content/images/untitled figure drone III/net.retorx.processedImages" 
mv "content/images/untitled figure I/untitled figure I-scaled.png" "content/images/untitled figure I/net.retorx.processedImages" 
mv "content/images/untitled figure II/untitled figure II-scaled.png" "content/images/untitled figure II/net.retorx.processedImages" 
mv "content/images/untitled figure III/untitled figure III aux-scaled.png" "content/images/untitled figure III/net.retorx.processedImages" 
mv "content/images/untitled figure III/untitled figure III-scaled.png" "content/images/untitled figure III/net.retorx.processedImages" 
mv "content/images/untitled figure IV/untitled figure IV aux-scaled.png" "content/images/untitled figure IV/net.retorx.processedImages" 
mv "content/images/untitled figure IV/untitled figure IV-scaled.png" "content/images/untitled figure IV/net.retorx.processedImages" 
mv "content/images/untitled figure IX/untitled figure IX-scaled.png" "content/images/untitled figure IX/net.retorx.processedImages" 
mv "content/images/untitled figure V/untitled figure V-scaled.png" "content/images/untitled figure V/net.retorx.processedImages" 
mv "content/images/untitled figure VI/untitled figure VI-scaled.png" "content/images/untitled figure VI/net.retorx.processedImages" 
mv "content/images/untitled figure VIII/untitled figure VIII-scaled.png" "content/images/untitled figure VIII/net.retorx.processedImages" 
mv "content/images/untitled figure X/untitled figure X-scaled.png" "content/images/untitled figure X/net.retorx.processedImages" 
mv "content/images/untitled figure XI/untitled figure XI-scaled.png" "content/images/untitled figure XI/net.retorx.processedImages" 
mv "content/images/untitled figure XII/untitled figure XII-scaled.png" "content/images/untitled figure XII/net.retorx.processedImages" 
mv "content/images/untitled figure XIX/untitled figure XIX-scaled.png" "content/images/untitled figure XIX/net.retorx.processedImages" 
mv "content/images/untitled figure XV/untitled figure XV-scaled.png" "content/images/untitled figure XV/net.retorx.processedImages" 
mv "content/images/untitled figure XVI/untitled figure XVI-scaled.png" "content/images/untitled figure XVI/net.retorx.processedImages" 
mv "content/images/untitled figure XVII/untitled figure XVII-scaled.png" "content/images/untitled figure XVII/net.retorx.processedImages" 
mv "content/images/untitled figure XVIII/untitled figure XVIII-scaled.png" "content/images/untitled figure XVIII/net.retorx.processedImages" 
mv "content/images/untitled figure XX/untitled figure XX-scaled.png" "content/images/untitled figure XX/net.retorx.processedImages" 
mv "content/images/untitled figure XXI/untitled figure XXI-scaled.png" "content/images/untitled figure XXI/net.retorx.processedImages" 
mv "content/images/Untitled Figure XXII/Untitled Figure XXII-scaled.png" "content/images/Untitled Figure XXII/net.retorx.processedImages" 
mv "content/images/untitled figures IV/untitled figures IV-scaled.png" "content/images/untitled figures IV/net.retorx.processedImages" 
mv "content/images/untitled form I/untitled form I aux-scaled.png" "content/images/untitled form I/net.retorx.processedImages" 
mv "content/images/untitled form I/untitled form I-scaled.png" "content/images/untitled form I/net.retorx.processedImages" 
mv "content/images/untitled form II/untitled form II-scaled.png" "content/images/untitled form II/net.retorx.processedImages" 
mv "content/images/untitled form III/untitled form III ayx-scaled.png" "content/images/untitled form III/net.retorx.processedImages" 
mv "content/images/untitled form III/untitled form III-scaled.png" "content/images/untitled form III/net.retorx.processedImages" 
mv "content/images/untitled machine I/untitled machine I-scaled.png" "content/images/untitled machine I/net.retorx.processedImages" 
mv "content/images/untitled machine II/untitled machine II-scaled.png" "content/images/untitled machine II/net.retorx.processedImages" 
mv "content/images/untitled machine II deconstructed/untitled machine II deconstructed-scaled.png" "content/images/untitled machine II deconstructed/net.retorx.processedImages" 
mv "content/images/untitled machine II deconstructed II/untitled machine II deconstructed II-scaled.png" "content/images/untitled machine II deconstructed II/net.retorx.processedImages" 
mv "content/images/untitled machine III/untitled machine III-scaled.png" "content/images/untitled machine III/net.retorx.processedImages" 
mv "content/images/untitled machine III heart/untitled machine III heart-scaled.png" "content/images/untitled machine III heart/net.retorx.processedImages" 
mv "content/images/untitled motion I/untitled motion I aux-scaled.png" "content/images/untitled motion I/net.retorx.processedImages" 
mv "content/images/untitled motion I/untitled motion I-scaled.png" "content/images/untitled motion I/net.retorx.processedImages" 
mv "content/images/untitled motion II/untitled motion II aux-scaled.png" "content/images/untitled motion II/net.retorx.processedImages" 
mv "content/images/untitled motion II/untitled motion II-scaled.png" "content/images/untitled motion II/net.retorx.processedImages" 
mv "content/images/untitled pose/untitled pose-scaled.png" "content/images/untitled pose/net.retorx.processedImages" 
mv "content/images/untitled recline III/untitled recline III-scaled.png" "content/images/untitled recline III/net.retorx.processedImages" 
mv "content/images/untitled reclining pose/untitled reclining pose-scaled.png" "content/images/untitled reclining pose/net.retorx.processedImages" 
mv "content/images/untitled texture IV/untitled texture IV-scaled.png" "content/images/untitled texture IV/net.retorx.processedImages" 
mv "content/images/upload/upload-scaled.png" "content/images/upload/net.retorx.processedImages" 
mv "content/images/US Bush Goss CIA/US Bush Goss CIA-scaled.png" "content/images/US Bush Goss CIA/net.retorx.processedImages" 
mv "content/images/velazquez christ revisited/velazquez christ revisited aux-scaled.png" "content/images/velazquez christ revisited/net.retorx.processedImages" 
mv "content/images/velazquez christ revisited/velazquez christ revisited-scaled.png" "content/images/velazquez christ revisited/net.retorx.processedImages" 
mv "content/images/war rider/war rider-scaled.png" "content/images/war rider/net.retorx.processedImages" 
mv "content/images/within/within-scaled.png" "content/images/within/net.retorx.processedImages" 
mv "content/images/WMSE website design/WMSE website design-scaled.png" "content/images/WMSE website design/net.retorx.processedImages" 
mv "content/images/WMSE website design II/WMSE website design II-scaled.png" "content/images/WMSE website design II/net.retorx.processedImages" 
mv "content/images/zombie trader is redundant/zombie trader is redundant aux1-scaled.png" "content/images/zombie trader is redundant/net.retorx.processedImages" 
mv "content/images/zombie trader is redundant/zombie trader is redundant-scaled.png" "content/images/zombie trader is redundant/net.retorx.processedImages" 
